server:
  port: 8080

spring:
  profiles:
    default: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2.client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile
        kakao:
          clientId: ${KAKAO_CLIENT_ID}
          clientSecret: ${KAKAO_CLIENT_SECRET}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: 'http://localhost:8080/login/oauth2/code/kakao'
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
        naver:
          clientId: ${NAVER_CLIENT_ID}
          clientSecret: ${NAVER_CLIENT_SECRET}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: 'http://localhost:8080/login/oauth2/code/naver'
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
      provider:
        kakao:
          authorizationUri: 'https://kauth.kakao.com/oauth/authorize'
          tokenUri: 'https://kauth.kakao.com/oauth/token'
          userInfoUri: 'https://kapi.kakao.com/v2/user/me'
          userNameAttribute: 'id'
        naver:
          authorizationUri: 'https://nid.naver.com/oauth2.0/authorize'
          tokenUri: 'https://nid.naver.com/oauth2.0/token'
          userInfoUri: 'https://openapi.naver.com/v1/nid/me'
          userNameAttribute: 'response'

# API 인증 설정
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - ${REDIRECT_URIS}

# JWT Secret Key 설정
jwt:
  secret: 'V33a0A1Vd081hjb3w43DSp667HK1ifVd081hjb3w33a0A1Vd081h'
