spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

app:
  auth:
    tokenSecret: 'V33a0A1Vd081hjb3w43DSp667HK1ifVd081hjb3w33a0A1Vd081h'
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect